// English dictionary — the canonical shape. `zh.ts` is typed `typeof en`, so any key
// missing from (or extra in) the Chinese dictionary is a compile error. That keeps the
// two languages in lockstep without a runtime i18n framework.
//
// Values are plain strings, or functions when a string needs interpolation. Annotate
// every function parameter: the inferred signatures here are what `zh.ts` is checked against.

export const en = {
  meta: {
    title: 'Engram · Memory Console',
  },

  // genuinely shared atoms (used across several pages/components)
  common: {
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    none: '(none)',
    remember: 'Remember',
    saveNewMemory: 'Save a new memory',
    mine: 'Set by me',
    updated: 'Updated',
    superseded: 'Superseded',
    toastDegraded: 'Saved as raw memory (extraction temporarily degraded)',
    toastRemembered: (n: number) => `Remembered — extracted ${n} new fact${n === 1 ? '' : 's'}`,
  },

  lang: {
    label: 'Language',
    zh: '中',
    en: 'EN',
    switchToZh: 'Switch to Chinese',
    switchToEn: 'Switch to English',
  },

  nav: {
    dashboard: 'Overview',
    profile: 'Profile',
    ask: 'Ask',
    facts: 'Facts',
    timeline: 'Timeline',
    graph: 'Graph',
    focus: 'Focus',
    conversations: 'Conversations',
    settings: 'Policy',
    privacy: 'Privacy',
    tagline: 'Open-source long-term memory engine · your memory is yours alone',
    consoleSub: 'Memory Console',
  },

  topbar: {
    online: 'Service online',
    offline: 'Service offline',
    logout: 'Sign out',
    logoutTitle: 'Sign out',
  },

  login: {
    title: 'Sign in to your memory space',
    subtitlePre:
      'Enter with an API key — in open mode the key is your namespace, so just pick any name. To dive in right away, use the public demo key ',
    subtitlePost: ' (a full memory is already loaded).',
    keyLabel: 'API Key',
    placeholder: 'e.g. 1 or sk-...',
    submit: 'Enter the console',
    footer: 'Your memory lives on your own server; only the holder of this key can reach it.',
  },

  dashboard: {
    loading: 'Loading your memory…',
    title: 'Overview',
    subtitle: (user: string) => `Hi ${user} — here's the full picture of your long-term memory`,
    toastWorking: 'Transient state → logged to history (queryable), but not added to your long-term profile',
    statLive: 'Current facts',
    statSuperseded: 'History (updated)',
    statEpisodes: 'Conversations',
    statSummaries: 'Summaries',
    rememberHint: 'System-1 write · System-2 async extraction / conflict resolution',
    rememberPlaceholder: "e.g. I'm in Shanghai next Tuesday for work, staying near the Bund.",
    quickSave: '⌘/Ctrl + Enter to save',
    personaHint: 'L3 persona · synthesized from current facts',
    personaTitle: 'Profile',
    personaEmptyTitle: 'Your profile is still forming',
    personaEmptyHint: 'Chat a bit more, or add a few entries under "Facts", and the profile builds itself.',
    recentAll: 'View all →',
    recentTitle: 'Recent facts',
    recentEmptyTitle: 'No facts yet',
    recentEmptyHint: 'Try saving a memory.',
  },

  ask: {
    title: 'Ask',
    subtitle:
      'Retrieve one small, distilled context to answer — exactly where Engram is leaner and more accurate than stuffing in the whole history',
    sectionUserProfile: 'User profile',
    sectionFacts: 'Relevant facts (with dates)',
    sectionTimeline: 'Timeline',
    sectionSummaries: 'Session summaries',
    sectionConversations: 'Source excerpts',
    placeholder: 'Ask anything, e.g. What are my coffee preferences?',
    searchBtn: 'Search',
    searching: 'Searching your memory…',
    answer: 'Answer',
    answerNote: 'Generated by the answering model from the memory context below.',
    lean: (n: number) => `Lean context ${n} tokens`,
    fullLabel: 'Full history',
    savings: (factor: string, pct: number) => `${factor}× leaner · only ${pct}%`,
    leanNote:
      'Only the relevant slice goes to the model, not the whole history — the longer the history, the more you save.',
    emptyTitle: 'No memory retrieved for this question yet',
    emptyHint: 'Try rephrasing, or save some memories first.',
  },

  timeline: {
    loading: 'Loading timeline…',
    title: 'Memory timeline',
    subtitle:
      'Bi-temporal view: watch memories evolve, get updated, and get superseded over time (newest on top)',
    legendLive: 'Currently valid',
    legendOld: 'Superseded',
    legendUpdate: '↑ Update',
    legendUpdateNote: 'this one updated an earlier value',
    emptyTitle: 'No facts to show yet',
    emptyHint: 'Save some memories first and the timeline grows on its own.',
  },

  graph: {
    loading: 'Building the graph…',
    title: 'Graph',
    subtitle: 'Entities and relations in semantic memory — multi-hop reasoning walks this very graph',
    legendLive: 'Current relation',
    legendOld: 'Invalidated',
    stats: (entities: number, relations: number) => `${entities} entities · ${relations} relations`,
    emptyTitle: 'The graph is still empty',
    emptyHint:
      'Chat more or add a few facts, and entities (people, places, things) and the relations between them will emerge. Hover a node to highlight its neighbors.',
    ariaLabel: 'Knowledge graph',
  },

  focus: {
    loading: 'Loading focus…',
    title: 'Focus',
    subtitle:
      "Customize what your memory emphasizes. This isn't cosmetic — it really changes retrieval ranking and what shows up in recall.",
    saved: 'Saved — tracked topics are boosted, muted topics are hidden',
    trackHint: 'Boost salience (retrieval score + resists forgetting/eviction)',
    trackTitle: 'Track',
    trackDescPre: 'Memories about these topics get ',
    trackDescEmph: 'weighted up',
    trackDescPost: ': ranked higher in retrieval and less likely to be forgotten or pushed out of the hot tier.',
    trackPlaceholder: 'e.g. work, health, family, AI',
    muteHint: 'Removed from recall context and profile',
    muteTitle: 'Mute',
    muteDescPre: 'Facts containing these words ',
    muteDescEmph: "won't appear",
    muteDescPost: ' in recall context or your profile (the data is kept; you can unmute anytime).',
    mutePlaceholder: 'e.g. weight, some old project',
  },

  conversations: {
    loading: 'Loading conversations…',
    title: 'Conversations',
    subtitle: 'The lossless raw memory stream (System-1), plus a per-entry session summary (L2)',
    toastWorking:
      "Transient state → logged to history (queryable later) + this session's working memory, but not written to your long-term profile",
    rememberPlaceholder: 'Write what you want it to remember here…',
    clearedWorking: "Cleared this session's working memory",
    clearSession: 'Clear this session',
    workingTitle: "Working memory · this session's transient state (history is saved separately and queryable)",
    expires: (date: string) => `expires ${date}`,
    episodesHint: (n: number) => `${n} ${n === 1 ? 'entry' : 'entries'}`,
    episodesTitle: 'Conversation log',
    summaryPrefix: 'Summary: ',
    emptyTitle: 'No conversations yet',
    emptyHint: 'Try saving one above.',
  },

  profile: {
    loading: 'Building structured profile…',
    title: 'Profile',
    subtitle:
      'A structured profile inferred from memory. Split into "confirmed" and "pending" — pending items don\'t enter the profile or affect recall; they just wait for your call.',
    evidenceUser: 'Set by you',
    evidenceReinforced: 'Reinforced',
    evidenceMentions: (n: number) => `mentioned in ${n} sessions`,
    evidenceOnce: 'mentioned once',
    evidenceTitle: 'Evidence source (honestly labeled, not a fabricated weight)',
    confirmed: (item: string) => `Confirmed: ${item} (promoted to set-by-you 🔒)`,
    dismissed: 'Candidate removed',
    emptyTitle: 'Your profile is still forming',
    emptyHint: 'Chat more or add a few facts, and the profile infers itself.',
    basicHint: 'Single-value identity slots',
    basicTitle: 'Basics',
    prefsHint: 'Confirmed · with like/dislike polarity, no fabricated weights',
    prefsTitle: 'Preferences',
    habitsHint: 'Behaviors / habits',
    habitsTitle: 'Habits',
    tentativeHint: "Mentioned once; not in the profile, doesn't affect recall",
    tentativeTitle: (n: number) => `Pending candidates · ${n}`,
    tentativeDescPre: 'These are inferences mentioned only once, ',
    tentativeDescEmph: 'not yet in the structured profile',
    tentativeDescPost:
      ' (but still in memory and usable during recall). Confirm to promote to "set by you" 🔒.',
    like: 'Like',
    dislike: 'Dislike',
    deleteCandidate: 'Remove candidate',
  },

  facts: {
    loading: 'Loading facts…',
    title: 'Facts',
    subtitle:
      "Every fact carries bi-temporal stamps and a source. Whatever you edit or add by hand is locked 🔒 and won't be overwritten by auto-extraction.",
    addManual: 'Add one manually',
    searchPlaceholder: 'Search facts…',
    showOld: 'Show history',
    hideSensitive: 'Hide sensitive',
    statusLive: 'Current',
    statusOld: 'Past',
    sensitive: 'Sensitive',
    invalidAt: (date: string) => `invalid since ${date}`,
    emptyTitle: 'No matching facts',
    emptyHint: 'Try another keyword, or add one manually.',
    editTitle: 'Edit fact',
    updated: 'Updated and locked 🔒',
    addTitle: 'Add a fact manually',
    added: 'Added (source: set by me)',
    deleteTitle: 'Permanently delete this memory?',
    deleteBody:
      'This is a user-initiated hard erase (unlike auto-invalidation, which keeps history). It cannot be undone afterward.',
    deleted: 'Deleted',
    conflictsHint: 'LLM-detected · you decide · never auto-overwritten',
    conflictsTitle: (n: number) => `Memory conflicts to review · ${n}`,
    conflictNew: 'New',
    conflictOld: 'Old',
    keepNewer: 'Keep newer (replace old)',
    keepNewerToast: 'Kept the newer one; the old one is invalidated',
    keepOlder: 'Keep older',
    keepOlderToast: 'Kept the older one',
    keepBoth: 'Keep both',
    keepBothToast: 'Ignored; both kept',
    subjectLabel: 'Subject',
    predicateLabel: 'Predicate',
    objectLabel: 'Object',
    objectPlaceholder: 'Acme Corp',
    markSensitive: 'Mark as sensitive (one-click exclude on export/share)',
    modalNote: 'Once saved, this is marked "set by me" and auto-extraction will not overwrite it.',
  },

  settings: {
    loading: 'Loading memory policy…',
    title: 'Memory policy',
    subtitle:
      'Customize "what to record" and the extraction / summary / persona prompts. Changes apply only to you and take effect on the next consolidation.',
    saved: 'Saved — applies on your next memory write / consolidation',
    promptExtractLabel: 'Extraction prompt',
    promptExtractHint: 'Decides which atomic facts (subject · predicate · object) get pulled from conversations',
    promptSummaryLabel: 'Summary prompt',
    promptSummaryHint: 'Decides how each session is compressed into an L2 summary',
    promptPersonaLabel: 'Persona prompt',
    promptPersonaHint: 'Decides how facts are synthesized into the L3 persona',
    recordHint: 'Appended to the extraction prompt; affects real extraction',
    recordTitle: 'What to record',
    recordDescPre: 'Tell the memory engine in plain language: ',
    recordDescEmph: 'what to emphasize and what to ignore',
    recordDescPost:
      '. E.g. "focus on my work projects, health data, and family info; ignore pleasantries and idle chit-chat".',
    recordPlaceholder:
      "e.g.:\n· Focus on my fitness plan, checkup metrics, reading notes\n· Don't record small talk like weather or greetings\n· Always include the date when money is involved",
    advancedToggle: 'Advanced: edit the prompts directly',
    defaultBadge: 'Default',
    customBadge: 'Customized',
    resetDefault: 'Reset to default',
    advancedNote:
      'Tip: leave these at default to use the built-in high-quality prompts; only edit when you want to change extraction behavior. Broke something? Hit "Reset to default".',
  },

  privacy: {
    title: 'Privacy & data',
    subtitle: 'Your memory is yours alone — export it in full anytime, or wipe it permanently in one click',
    exportedExcl: 'Download started (sensitive data excluded)',
    exported: 'Download of your data started',
    exportHint: 'Right to data portability',
    exportTitle: 'Export my data',
    exportDesc:
      'Download a complete JSON: your profile, every fact (with bi-temporal stamps, source, provenance), raw conversations, session summaries, focus, and the graph.',
    excludeSensitive: 'Exclude sensitive data (health / finance / IDs, etc.)',
    exportBtn: 'Export all data (JSON)',
    forgetHint: 'Right to be forgotten',
    forgetTitle: 'Wipe my memory',
    forgetDesc:
      'Permanently delete all memory under this key — facts, conversations, summaries, profile, focus — every bit erased, unrecoverable.',
    forgetBtn: 'Wipe permanently',
    selfHostTitle: 'Local-first, self-hostable',
    selfHostBody:
      'Engram is open source (AGPL-3.0; commercial use needs a separate license). Memory is stored as files on your own server by default, isolated per API key. Without this key, no one can see your memory.',
    confirmTitle: (user: string) => `Permanently wipe all memory for "${user}"?`,
    confirmLabel: 'Yes, delete everything',
    confirmBodyPre: 'This action is ',
    confirmBodyEmph: 'irreversible',
    confirmBodyPost: '. We recommend exporting a backup before you continue.',
    forgotten: 'All your memory has been wiped',
  },

  errors: {
    unauthorized: 'Your API key is invalid or has expired. Please sign in again.',
    requestFailed: (status: number) => `Request failed (${status})`,
    exportFailed: (status: number) => `Export failed (${status})`,
  },
}

export type Dict = typeof en
